### ISSUE TITLE
custom data trainning

### ISSUE THREAD

**Issue by zhangyunming** [Reagan1311/DABNet#10]
hi，你好，我想咨询下两个问题：

 1.  如果我只想用指定的一个卡，是不是可以直接在train.py中改为1（我想用第2张卡）
 2.  如果我训练的数据只有两类，怎么修改cityscapes.pkl中的内容，如class_weights等

谢谢啊，老铁

**Comment by Reagan1311** [comment]
1.是的
2.这个要修改cityscapes.py中的cityscapesTrainInform函数，需要重新计算class_weights
