### ISSUE TITLE
questions about results

### ISSUE THREAD

**Issue by cians** [Reagan1311/DABNet#11]
Thank you for sharing the code!
I have some questions that I hope you can answer:
1.Is cityscapes_val_list.txt  xxxx_gtFine_labelTrainIds.png the same as xxx_gtFine_labelIds.png in original dataset?

cityscapes_val_list.txt label里的文件名,和原始dataset的label名略有不同, 是一样的吗?

2.Is the [model](https://drive.google.com/open?id=1ZKGBQogSqxyKD-QIJgzyDXw2TR0HUePA) behind the mIOU 69.57%  means its performance is 69.57% ? 

你在results 里放在google dirve里的cityscapes model 是对应结果mIOU 69.57​%的模型吗?
我测得的有问题, 0.6%

thank you!

**Comment by Reagan1311** [comment]
1 These two files are different, labelIds.png has 33 categories, while trainIds.png transfer to 19 categories.
2. Yes. I tested before, it worked well, maybe your checkpoint path is not right.
