### ISSUE TITLE
cityscapes训练的问题

### ISSUE THREAD

**Issue by LxxxxK** [Reagan1311/DABNet#12]
camvid数据集没有问题，但是当我训练cityscapes数据集，debug时‘ProbOhemCrossEntropy2d(nn.Module)’出现以下问题
![image](https://user-images.githubusercontent.com/53500107/65384617-d8754200-dd56-11e9-9967-3bb3086f6fdf.png)
由于显存不够，我用的batchsize是2，希望大佬有时间时能回复下，谢谢您

**Comment by Reagan1311** [comment]
代码在我电脑上没有这个问题诶，你把.long()改成.double()试试

**Comment by LxxxxK** [comment]
![image](https://user-images.githubusercontent.com/53500107/65419321-fa42f780-de30-11e9-87ca-0ce6a9327803.png)
依然没有用，我尝试把cityscape数据集的’ProbOhemCrossEntropy2d‘损失函数换成’CrossEntropyLoss2d‘是可以训练的，请问这两个损失函数对结果有多大的影响？谢谢您

**Comment by Reagan1311** [comment]
影响不大，大概在1%以内
