### ISSUE TITLE
I got 76.67fps on 1080Ti

### ISSUE THREAD

**Issue by BaobeiChenchen** [Reagan1311/DABNet#14]
Here is the output:
```
python eval_fps.py 512,1024
=========Speed Testing=========
Elapsed Time: [1.30 s / 100 iter]
Speed Time: 13.04 ms / iter   FPS: 76.69
```

And  on the resolution of 1024,2048 it's even more slower.
```
 CUDA_VISIBLE_DEVICES=0 python eval_fps.py 1024,2048
=========Speed Testing=========
Elapsed Time: [4.95 s / 100 iter]
Speed Time: 49.51 ms / iter   FPS: 20.20
```

**Comment by Reagan1311** [comment]
#4 Please refer to this issue, you should clear the GPU occupation then test the fps

**Comment by wk524629918** [comment]
> Here is the output:
> 
> ```
> python eval_fps.py 512,1024
> =========Speed Testing=========
> Elapsed Time: [1.30 s / 100 iter]
> Speed Time: 13.04 ms / iter   FPS: 76.69
> ```
> 
> And on the resolution of 1024,2048 it's even more slower.
> 
> ```
>  CUDA_VISIBLE_DEVICES=0 python eval_fps.py 1024,2048
> =========Speed Testing=========
> Elapsed Time: [4.95 s / 100 iter]
> Speed Time: 49.51 ms / iter   FPS: 20.20
> ```
Have you solved the problem?
