### ISSUE TITLE
关于cityscapes数据集结果的问题

### ISSUE THREAD

**Issue by LxxxxK** [Reagan1311/DABNet#15]
首先跟您说一下国庆节快乐。
1、在您的paper中，table2的DABNet-baseline的mIoU是69.1，而Table3中DABNet是70.1，请问这两个结果有什么不同？
2、我执行了'python test.py --dataset cityscapes --checkpoint .....pth'结果最好的是68.2，我还没有提交到cityscapes官网进行测试，请问这两个结果差距大吗？期望能得到您的回复。谢谢

**Comment by Reagan1311** [comment]
不用这么客气，我也是小白 : )
1. 一个是只用了train set进行训练，另一个则用了tran+val进行训练
2. 我记得你之前说过你的显存不够，如果batchsize很小的话，SGD根据小batch进行的反向传播会很难收敛，所以相应的结果也会受影响，如果你要提交测试的话，就在train+val进行训练

**Comment by ChenJiafei0722** [comment]
> 首先跟您说一下国庆节快乐。 1、在您的paper中，table2的DABNet-baseline的mIoU是69.1，而Table3中DABNet是70.1，请问这两个结果有什么不同？ 2、我执行了'python test.py --dataset cityscapes --checkpoint .....pth'结果最好的是68.2，我还没有提交到cityscapes官网进行测试，请问这两个结果差距大吗？期望能得到您的回复。谢谢

您好，请问您cityscapes数据集的结果，提交到官网评估了吗？怎样提交到官网进行评估呢？请教一下您，麻烦啦。
