### ISSUE TITLE
questions about predict.py

### ISSUE THREAD

**Issue by lj107024** [Reagan1311/DABNet#16]
I have solved this problem! Thanks!
** you can use `predict.py` to save all the output images, then submit to official webpage for evaluation.**

I have run the test command, and the segmentation result graph is ok, but i submit to official webpage for evaluation score results, the iou classes is 0.0224... many classes are scored 0. i'm quite confused, the result of val is ok , why the test set is not? so i want to know is there any other operation needed before run this predict.py ?

**Comment by Reagan1311** [comment]
Hi, before you submit the output images, you should first use the `utils/trainID2labelID.py` to convert the train ID, that's cityscapes webpage evaluation requirement.
