### ISSUE TITLE
PyTorch error on camvid predictions (size mismatch)

### ISSUE THREAD

**Issue by niskov** [Reagan1311/DABNet#2]
When running the following command:

`python` predict.py --checkpoint DABNet_camvid.pth

I received the following error:

> RuntimeError: Error(s) in loading state_dict for DABNet:

        size mismatch for classifier.0.conv.weight: copying a param with shape torch.Size([11, 259, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 259, 1, 1]).

**Comment by Reagan1311** [comment]
predict.py is mainly for cityscapes test set (output the predicted image and submit to the official webpage for evaluation), if you want to test the result on camvid.
You should run with following command:
`python test.py --dataset camvid --checkpoint DABNet_camvid.pth`
