### ISSUE TITLE
How did you calculate the weights used in the loss function?

### ISSUE THREAD

**Issue by Yusheng179** [Reagan1311/DABNet#26]
I find that you have used the weight = torch.FloatTensor([0.8373, 0.918, 0.866, 1.0345, 1.0166, 0.9969, 0.9754, 1.0489, 0.8786, 1.0023, 0.9539, 0.9843, 1.1116, 0.9037, 1.0865, 1.0955, 1.0865, 1.1529, 1.0507]) in the loss function to deal with the problem of class imbalance. Can you tell me how you got it?

**Comment by Reagan1311** [comment]
This weight setting refers to other code, and weights are calculated through all the cityscapes datase images.
