### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by xshan786** [Reagan1311/DABNet#27]
sorry for asking again this question because its closed or not answered.
so i am getting same error 
" return image.copy(), label.copy(), np.array(size), name
AttributeError: 'NoneType' object has no attribute 'copy'' while i am running test.py.
Could you please guide me.

**Comment by Reagan1311** [comment]
That means the image and the label are None, so maybe the path of these files is not correct

**Comment by xshan786** [comment]
Thank you
