### ISSUE TITLE
cv2.error: 

### ISSUE THREAD

**Issue by shifangtian** [Reagan1311/DABNet#28]
Thank you for sharing the code. When I run the train.py, I get this error. My dataset folder is the same as the example, but it always shows that the image data cannot be found. Can you help me?
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by Reagan1311** [comment]
#7 you can refer to this question and check the file name, if it is not the same with the txt file, you need to transfer the label file into 19 categories.

**Comment by shifangtian** [comment]
I am very grateful that you can reply to me so quickly. I checked my data and the name of the txt list and found that the file name of the tag is different. It will be fine after modification. Does the parameters in your source code get 70% of the mIou parameters?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gen Li"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 晚上6:14
收件人:&nbsp;"Reagan1311/DABNet"<DABNet@noreply.github.com&gt;;
抄送:&nbsp;"剑可入鞘否"<404716439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Reagan1311/DABNet] cv2.error:  (#28)




#7 you can refer to this question and check the file name, if it is not the same with the txt file, you need to transfer the label file into 19 categories.

**Comment by Reagan1311** [comment]
yes, it can get 70% mIoU in full resolution image (1024 x 2048)
