### ISSUE TITLE
Prediction on resized image

### ISSUE THREAD

**Issue by xshan786** [Reagan1311/DABNet#29]
Hello, i want to make prediction on resized image. i means that i want to rescale image from (1024x2048) to (512X1024) to increase fps. but when i use predict function to do prediction. it throw me error.
"self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same."

can you please help me to solve this problem.

**Comment by Reagan1311** [comment]
Hi, there is a `cityscapes.py` in the dataset folder, where you can find a f_scale in the function `CityscapesValDataSet`, you can change this to rescale the image.
