### ISSUE TITLE
关于提交到测试服务器的问题

### ISSUE THREAD

**Issue by GitHubLiaoYong** [Reagan1311/DABNet#32]
**_您好，首先感谢您的工作。我自己设计了一个网络，然后想提交到cityscapes官网测试，用的是predict.py文件。在您的test文件下载验证集上MIoU有75，但是用您的predict.py生成的图片提交到官网之后，很多类的iou是0，且最终结果如图。我看了您的代码好像生成的预测id是训练id，而cityscapes提交的要求是实际id，如车的id应该是26。如果您看到了，希望帮忙解决这个问题。
![图片](https://user-images.githubusercontent.com/42443308/71758372-b2c11280-2ed9-11ea-8d08-b3d818a30f86.png)

**Comment by GitHubLiaoYong** [comment]
您好，我在您的项目里找到了将TrainId转化为ID的代码，等48小时之后再提交看看结果。

**Comment by Michaela222** [comment]
你好，请问一下将TrainId转化为ID的代码是在哪个文件里呀。

**Comment by ChenJiafei0722** [comment]
> 您好，我在您的项目里找到了将TrainId转化为ID的代码，等48小时之后再提交看看结果。

您好，请问怎么在官网提交结果，进行测试呢？

**Comment by Michaela222** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
