### ISSUE TITLE
45 fps instead of the claimed 100 fps

### ISSUE THREAD

**Issue by IssamLaradji** [Reagan1311/DABNet#4]
Hi there,
This is amazing work. I am using Nvidia Tesla P100 GPU and I am getting 45 fps when running `eval_fps.py`. Is there a reason I am not getting  104.2 fps (as claimed in the paper)?

**Comment by Reagan1311** [comment]
Although Tesla P100 is inferior than 1080Ti, but it shouldn't be so huge difference.
When you test the speed, you need to clear the GPU occupation, otherwise you will get a very low fps.

**Comment by wk524629918** [comment]
> Although Tesla P100 is inferior than 1080Ti, but it shouldn't be so huge difference.
> When you test the speed, you need to clear the GPU occupation, otherwise you will get a very low fps.
My GPU occupation is 1M, but it's still very slow

**Comment by wk524629918** [comment]
> Hi there,
> This is amazing work. I am using Nvidia Tesla P100 GPU and I am getting 45 fps when running `eval_fps.py`. Is there a reason I am not getting 104.2 fps (as claimed in the paper)?

Hello, have you solved this problem?
