### ISSUE TITLE
Question about the result

### ISSUE THREAD

**Issue by Serge-weihao** [Reagan1311/DABNet#6]
![图片](https://user-images.githubusercontent.com/40890323/63647982-627fba00-c75b-11e9-8b46-9d2c7c2f9dc6.png)
![图片](https://user-images.githubusercontent.com/40890323/63647997-c4d8ba80-c75b-11e9-87c2-e1653249ce16.png)
![图片](https://user-images.githubusercontent.com/40890323/63648047-7ed02680-c75c-11e9-9e0e-871895697ec8.png)

It seems that your submission is under 1024X2048(no subsampling) not 512X1024, whose size is different from the descriptions in your paper and code in eval_fps.py. So I am confused about this and want to know under what input size of testing you can get 70.1 mIoU and 104.2 FPS.

**Comment by Reagan1311** [comment]
the mIoU is computed under the full size (1024X2048), while the input size for training is 512X1024.
If you read the paper, you can know the 104 FPS is the speed of 512X1024, and we also give the FPS of 256X512 and 1024X2048 (Table5)
