### ISSUE TITLE
在训练时遇到一些问题

### ISSUE THREAD

**Issue by LxxxxK** [Reagan1311/DABNet#7]
我输入`python train.py --dataset cityscapes` 后出现如下错误
![image](https://user-images.githubusercontent.com/53500107/63865006-67ef3580-c9e3-11e9-9042-60f4a0a85509.png)
我想问您下是路径的问题还是其他问题，我能否看下您的'cityscape.py'文件是怎样设置的嘛，谢谢大佬，这是我的路径设置方式
![image](https://user-images.githubusercontent.com/53500107/63865685-928dbe00-c9e4-11e9-9fba-a69e27a2dc7d.png)
谢谢大佬

**Comment by Reagan1311** [comment]
root应该设置为你存放cityscapes数据集的文件，比如root="dataset/cityscapes"
path应该设置为你需要训练的txt文件，比如list=“dataset/cityscapes/cityscapes_train_list.txt”
但是这些不用在cityscapes.py里面设置的，在`builders/dataset_builder.py`都已经设置好了，所以在cityscapes.py里，root和path_list设置为空就行
根据你的错误，问题出在了label的载入，train data的载入是没有问题的，可能你没有把label放在cityscapes文件夹下，或者没有正确的命名为`gtFine`

**Comment by LxxxxK** [comment]
> root应该设置为你存放cityscapes数据集的文件，比如root="dataset/cityscapes"
> path应该设置为你需要训练的txt文件，比如list=“dataset/cityscapes/cityscapes_train_list.txt”
> 但是这些不用在cityscapes.py里面设置的，在`builders/dataset_builder.py`都已经设置好了，所以在cityscapes.py里，root和path_list设置为空就行
> 根据你的错误，问题出在了label的载入，train data的载入是没有问题的，可能你没有把label放在cityscapes文件夹下，或者没有正确的命名为`gtFine`

我是正确命名的gtFine，而且当我运行CamVid数据集也是出现相同问题
![image](https://user-images.githubusercontent.com/53500107/63934721-9413c080-ca8e-11e9-9fff-2531b0348fcf.png)

**Comment by Reagan1311** [comment]
这个错误说明了你label图片载入有问题，所以open-cv不能进行resize，但是我不清楚你的文件情况，你得自己检查一下是不是label的路径和我的不一致

**Comment by wk524629918** [comment]
> 我输入`python train.py --dataset cityscapes` 后出现如下错误
> ![image](https://user-images.githubusercontent.com/53500107/63865006-67ef3580-c9e3-11e9-9042-60f4a0a85509.png)
> 我想问您下是路径的问题还是其他问题，我能否看下您的'cityscape.py'文件是怎样设置的嘛，谢谢大佬，这是我的路径设置方式
> ![image](https://user-images.githubusercontent.com/53500107/63865685-928dbe00-c9e4-11e9-9fba-a69e27a2dc7d.png)
> 谢谢大佬
我也有同样的问题，请问你解决了吗

**Comment by wk524629918** [comment]
我也有同样的问题，请问你解决了吗？

**Comment by LxxxxK** [comment]
@wk524629918 解决了，其实是你label的问题，你去/dataset/cityscapes/的****.txt文件看一下每个文件的名字，然后去你数据集看一下你gtFine里的label名字是否一样，不一样的话就用cityscapesscript处理一下，很有可能你的gtFine不是19类，这是大家默认的东西，所以作者没有提到
