### ISSUE TITLE
different test batch_size 

### ISSUE THREAD

**Issue by lu123456789** [Reagan1311/DABNet#8]
Hello,i changed batch_size=1 to batch_size=batch_size when test. When i test the same model with different batch_sizes, why miou are different?

**Comment by Reagan1311** [comment]
I think the main reason is the mIoU calculation function, the code is for batch size 1.
Besides, you can't randomly set the batch_size, as the total number of images is 500
You should set the number that is divisible by 500, otherwise the last batch will contain the different number of image.

**Comment by lu123456789** [comment]
thank you
